# Data
path: C:/Users/User/PycharmProjects/Yolov8/data
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Keypoints
kpt_shape: [13, 3]   # [number of keypoints, number of dim]
flip_idx: [0, 4, 5, 6, 1, 2, 3, 10, 11, 12, 7, 8, 9]  # left-right flip pairs

# Classes
names:
  0: swimming
